name = "lnmai-core"
version = "0.1.0"
defaultTargets = ["lnmai-core"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.29.0"

[[lean_lib]]
name = "LnmaiCore"

[[lean_exe]]
name = "lnmai-core"
root = "Main"

[[lean_exe]]
name = "real-chart-verification"
root = "RealChartVerification"
