-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lnmai_core]: function definitions
import Aeneas
import LnmaiCore.Types
import LnmaiCore.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lnmai_core

/-- Trait implementation: [core::array::{impl core::fmt::Debug for [T; N]}]
    Source: '/rustc/library/core/src/array/mod.rs', lines 355:0-355:57
    Name pattern: [core::fmt::Debug<[@T; @N]>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<[@T; @N]>"]
def Array.Insts.CoreFmtDebug {T : Type} (N : Std.Usize) (fmtDebugInst :
  core.fmt.Debug T) : core.fmt.Debug (Array T N) := {
  fmt := core.array.DebugArray.fmt fmtDebugInst
}

/-- Trait implementation: [core::default::{impl core::default::Default for bool}]
    Source: '/rustc/library/core/src/default.rs', lines 154:8-154:33
    Name pattern: [core::default::Default<bool>] -/
@[reducible, rust_trait_impl "core::default::Default<bool>"]
def Bool.Insts.CoreDefaultDefault : core.default.Default Bool := {
  default := core.default.DefaultBool.default
}

/-- Trait implementation: [core::fmt::float::{impl core::fmt::Debug for f64}]
    Source: '/rustc/library/core/src/fmt/float.rs', lines 209:12-209:30
    Name pattern: [core::fmt::Debug<f64>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<f64>"]
def F64.Insts.CoreFmtDebug : core.fmt.Debug F64 := {
  fmt := F64.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [core::fmt::{impl core::fmt::Display for &'_0 T}]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2871:8-2871:46
    Name pattern: [core::fmt::Display<&'0 @T>] -/
@[reducible, rust_trait_impl "core::fmt::Display<&'0 @T>"]
def Shared0T.Insts.CoreFmtDisplay {T : Type} (DisplayInst : core.fmt.Display T)
  : core.fmt.Display T := {
  fmt := Shared0T.Insts.CoreFmtDisplay.fmt DisplayInst
}

/-- Trait implementation: [core::fmt::{impl core::fmt::Display for str}]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2965:0-2965:20
    Name pattern: [core::fmt::Display<str>] -/
@[reducible, rust_trait_impl "core::fmt::Display<str>"]
def Str.Insts.CoreFmtDisplay : core.fmt.Display Str := {
  fmt := Str.Insts.CoreFmtDisplay.fmt
}

/-- Trait implementation: [core::fmt::{impl core::fmt::Debug for (U, T)}]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 3087:12-3087:57
    Name pattern: [core::fmt::Debug<(@U, @T)>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<(@U, @T)>"]
def Pair.Insts.CoreFmtDebug {U : Type} {T : Type} (DebugInst : core.fmt.Debug
  U) (DebugInst1 : core.fmt.Debug T) : core.fmt.Debug (U × T) := {
  fmt := Pair.Insts.CoreFmtDebug.fmt DebugInst DebugInst1
}

/-- Trait implementation: [core::fmt::num::imp::{impl core::fmt::Display for i64}]
    Source: '/rustc/library/core/src/fmt/num.rs', lines 155:8-155:37
    Name pattern: [core::fmt::Display<i64>] -/
@[reducible, rust_trait_impl "core::fmt::Display<i64>"]
def I64.Insts.CoreFmtDisplay : core.fmt.Display Std.I64 := {
  fmt := core.fmt.num.imp.DisplayI64.fmt
}

/-- Trait implementation: [core::num::{impl core::str::traits::FromStr<core::num::error::ParseIntError> for i64}]
    Source: '/rustc/library/core/src/num/mod.rs', lines 1589:8-1589:38
    Name pattern: [core::str::traits::FromStr<i64, core::num::error::ParseIntError>] -/
@[reducible, rust_trait_impl
  "core::str::traits::FromStr<i64, core::num::error::ParseIntError>"]
def I64.Insts.CoreStrTraitsFromStrParseIntError : core.str.traits.FromStr
  Std.I64 core.num.error.ParseIntError := {
  from_str := I64.Insts.CoreStrTraitsFromStrParseIntError.from_str
}

/-- Trait implementation: [core::option::{impl core::fmt::Debug for core::option::Option<T>}]
    Source: '/rustc/library/core/src/option.rs', lines 591:15-591:20
    Name pattern: [core::fmt::Debug<core::option::Option<@T>>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<core::option::Option<@T>>"]
def core.option.Option.Insts.CoreFmtDebug {T : Type} (fmtDebugInst :
  core.fmt.Debug T) : core.fmt.Debug (Option T) := {
  fmt := core.option.Option.Insts.CoreFmtDebug.fmt fmtDebugInst