-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lnmai_core]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lnmai_core

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2492:4-2501:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish"]
axiom core.fmt.Formatter.debug_struct_field3_finish
  :
  core.fmt.Formatter → Str → Str → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Str → Dyn (fun _dyn
    => core.fmt.Debug _dyn) → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [lnmai_core::aeneas_test::Grade]
    Source: 'src/aeneas_test.rs', lines 8:0-13:1
    Visibility: public -/
@[discriminant isize]
inductive aeneas_test.Grade where
| Miss : aeneas_test.Grade
| Good : aeneas_test.Grade
| Great : aeneas_test.Grade
| Perfect : aeneas_test.Grade

/-- [lnmai_core::aeneas_test::{impl core::fmt::Debug for lnmai_core::aeneas_test::Grade}::fmt]:
    Source: 'src/aeneas_test.rs', lines 7:9-7:14
    Visibility: public -/
def aeneas_test.Grade.Insts.CoreFmtDebug.fmt
  (self : aeneas_test.Grade) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | aeneas_test.Grade.Miss => core.fmt.Formatter.write_str f (toStr "Miss")
  | aeneas_test.Grade.Good => core.fmt.Formatter.write_str f (toStr "Good")
  | aeneas_test.Grade.Great => core.fmt.Formatter.write_str f (toStr "Great")
  | aeneas_test.Grade.Perfect =>
    core.fmt.Formatter.write_str f (toStr "Perfect")

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::fmt::Debug for lnmai_core::aeneas_test::Grade}]
    Source: 'src/aeneas_test.rs', lines 7:9-7:14 -/
@[reducible]
def aeneas_test.Grade.Insts.CoreFmtDebug : core.fmt.Debug aeneas_test.Grade
  := {
  fmt := aeneas_test.Grade.Insts.CoreFmtDebug.fmt
}

/-- [lnmai_core::aeneas_test::{impl core::clone::Clone for lnmai_core::aeneas_test::Grade}::clone]:
    Source: 'src/aeneas_test.rs', lines 7:16-7:21
    Visibility: public -/
def aeneas_test.Grade.Insts.CoreCloneClone.clone
  (self : aeneas_test.Grade) : Result aeneas_test.Grade := do
  ok self

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::clone::Clone for lnmai_core::aeneas_test::Grade}]
    Source: 'src/aeneas_test.rs', lines 7:16-7:21 -/
@[reducible]
def aeneas_test.Grade.Insts.CoreCloneClone : core.clone.Clone aeneas_test.Grade
  := {
  clone := aeneas_test.Grade.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::marker::Copy for lnmai_core::aeneas_test::Grade}]
    Source: 'src/aeneas_test.rs', lines 7:23-7:27 -/
@[reducible]
def aeneas_test.Grade.Insts.CoreMarkerCopy : core.marker.Copy aeneas_test.Grade
  := {
  cloneInst := aeneas_test.Grade.Insts.CoreCloneClone
}

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::marker::StructuralPartialEq for lnmai_core::aeneas_test::Grade}]
    Source: 'src/aeneas_test.rs', lines 7:29-7:38 -/
@[reducible]
def aeneas_test.Grade.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq aeneas_test.Grade := {
}

/-- [lnmai_core::aeneas_test::{impl core::cmp::PartialEq<lnmai_core::aeneas_test::Grade> for lnmai_core::aeneas_test::Grade}::eq]:
    Source: 'src/aeneas_test.rs', lines 7:29-7:38
    Visibility: public -/
def aeneas_test.Grade.Insts.CoreCmpPartialEqGrade.eq
  (self : aeneas_test.Grade) (other : aeneas_test.Grade) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::PartialEq<lnmai_core::aeneas_test::Grade> for lnmai_core::aeneas_test::Grade}]
    Source: 'src/aeneas_test.rs', lines 7:29-7:38 -/
@[reducible]
def aeneas_test.Grade.Insts.CoreCmpPartialEqGrade : core.cmp.PartialEq
  aeneas_test.Grade aeneas_test.Grade := {
  eq := aeneas_test.Grade.Insts.CoreCmpPartialEqGrade.eq
}

/-- [lnmai_core::aeneas_test::{impl core::cmp::Eq for lnmai_core::aeneas_test::Grade}::assert_fields_are_eq]:
    Source: 'src/aeneas_test.rs', lines 7:40-7:42
    Visibility: public -/
def aeneas_test.Grade.Insts.CoreCmpEq.assert_fields_are_eq
  (self : aeneas_test.Grade) : Result Unit := do
  ok ()

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::Eq for lnmai_core::aeneas_test::Grade}]
    Source: 'src/aeneas_test.rs', lines 7:40-7:42 -/
@[reducible]
def aeneas_test.Grade.Insts.CoreCmpEq : core.cmp.Eq aeneas_test.Grade := {
  partialEqInst := aeneas_test.Grade.Insts.CoreCmpPartialEqGrade
  assert_fields_are_eq :=
    aeneas_test.Grade.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [lnmai_core::aeneas_test::NoteType]
    Source: 'src/aeneas_test.rs', lines 17:0-21:1
    Visibility: public -/
@[discriminant isize]
inductive aeneas_test.NoteType where
| Tap : aeneas_test.NoteType
| Hold : aeneas_test.NoteType
| Slide : aeneas_test.NoteType

/-- [lnmai_core::aeneas_test::{impl core::fmt::Debug for lnmai_core::aeneas_test::NoteType}::fmt]:
    Source: 'src/aeneas_test.rs', lines 16:9-16:14
    Visibility: public -/
def aeneas_test.NoteType.Insts.CoreFmtDebug.fmt
  (self : aeneas_test.NoteType) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | aeneas_test.NoteType.Tap => core.fmt.Formatter.write_str f (toStr "Tap")
  | aeneas_test.NoteType.Hold => core.fmt.Formatter.write_str f (toStr "Hold")
  | aeneas_test.NoteType.Slide =>
    core.fmt.Formatter.write_str f (toStr "Slide")

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::fmt::Debug for lnmai_core::aeneas_test::NoteType}]
    Source: 'src/aeneas_test.rs', lines 16:9-16:14 -/
@[reducible]
def aeneas_test.NoteType.Insts.CoreFmtDebug : core.fmt.Debug
  aeneas_test.NoteType := {
  fmt := aeneas_test.NoteType.Insts.CoreFmtDebug.fmt
}

/-- [lnmai_core::aeneas_test::{impl core::clone::Clone for lnmai_core::aeneas_test::NoteType}::clone]:
    Source: 'src/aeneas_test.rs', lines 16:16-16:21
    Visibility: public -/
def aeneas_test.NoteType.Insts.CoreCloneClone.clone
  (self : aeneas_test.NoteType) : Result aeneas_test.NoteType := do
  ok self

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::clone::Clone for lnmai_core::aeneas_test::NoteType}]
    Source: 'src/aeneas_test.rs', lines 16:16-16:21 -/
@[reducible]
def aeneas_test.NoteType.Insts.CoreCloneClone : core.clone.Clone
  aeneas_test.NoteType := {
  clone := aeneas_test.NoteType.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::marker::Copy for lnmai_core::aeneas_test::NoteType}]
    Source: 'src/aeneas_test.rs', lines 16:23-16:27 -/
@[reducible]
def aeneas_test.NoteType.Insts.CoreMarkerCopy : core.marker.Copy
  aeneas_test.NoteType := {
  cloneInst := aeneas_test.NoteType.Insts.CoreCloneClone
}

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::marker::StructuralPartialEq for lnmai_core::aeneas_test::NoteType}]
    Source: 'src/aeneas_test.rs', lines 16:29-16:38 -/
@[reducible]
def aeneas_test.NoteType.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq aeneas_test.NoteType := {
}

/-- [lnmai_core::aeneas_test::{impl core::cmp::PartialEq<lnmai_core::aeneas_test::NoteType> for lnmai_core::aeneas_test::NoteType}::eq]:
    Source: 'src/aeneas_test.rs', lines 16:29-16:38
    Visibility: public -/
def aeneas_test.NoteType.Insts.CoreCmpPartialEqNoteType.eq
  (self : aeneas_test.NoteType) (other : aeneas_test.NoteType) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::PartialEq<lnmai_core::aeneas_test::NoteType> for lnmai_core::aeneas_test::NoteType}]
    Source: 'src/aeneas_test.rs', lines 16:29-16:38 -/
@[reducible]
def aeneas_test.NoteType.Insts.CoreCmpPartialEqNoteType : core.cmp.PartialEq
  aeneas_test.NoteType aeneas_test.NoteType := {
  eq := aeneas_test.NoteType.Insts.CoreCmpPartialEqNoteType.eq
}

/-- [lnmai_core::aeneas_test::{impl core::cmp::Eq for lnmai_core::aeneas_test::NoteType}::assert_fields_are_eq]:
    Source: 'src/aeneas_test.rs', lines 16:40-16:42
    Visibility: public -/
def aeneas_test.NoteType.Insts.CoreCmpEq.assert_fields_are_eq
  (self : aeneas_test.NoteType) : Result Unit := do
  ok ()

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::Eq for lnmai_core::aeneas_test::NoteType}]
    Source: 'src/aeneas_test.rs', lines 16:40-16:42 -/
@[reducible]
def aeneas_test.NoteType.Insts.CoreCmpEq : core.cmp.Eq aeneas_test.NoteType
  := {
  partialEqInst := aeneas_test.NoteType.Insts.CoreCmpPartialEqNoteType
  assert_fields_are_eq :=
    aeneas_test.NoteType.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [lnmai_core::aeneas_test::grade_dist]:
    Source: 'src/aeneas_test.rs', lines 24:0-31:1
    Visibility: public -/
def aeneas_test.grade_dist (g : aeneas_test.Grade) : Result Std.U32 := do
  match g with
  | aeneas_test.Grade.Miss => ok 3#u32
  | aeneas_test.Grade.Good => ok 2#u32
  | aeneas_test.Grade.Great => ok 1#u32
  | aeneas_test.Grade.Perfect => ok 0#u32

/-- [lnmai_core::aeneas_test::base_score]:
    Source: 'src/aeneas_test.rs', lines 34:0-40:1
    Visibility: public -/
def aeneas_test.base_score (nt : aeneas_test.NoteType) : Result Std.U32 := do
  match nt with
  | aeneas_test.NoteType.Tap => ok 500#u32
  | aeneas_test.NoteType.Hold => ok 1000#u32
  | aeneas_test.NoteType.Slide => ok 1500#u32

/-- [lnmai_core::aeneas_test::compute_score]:
    Source: 'src/aeneas_test.rs', lines 43:0-50:1
    Visibility: public -/
def aeneas_test.compute_score
  (base : Std.U32) (grade : aeneas_test.Grade) :
  Result (Std.U32 × Std.U32)
  := do
  match grade with
  | aeneas_test.Grade.Miss => ok (0#u32, base)
  | aeneas_test.Grade.Good =>
    let i ← base / 2#u32
    let i1 ← base - i
    ok (i, i1)
  | aeneas_test.Grade.Great =>
    let i ← base * 4#u32
    let i1 ← i / 5#u32
    let i2 ← i / 5#u32
    let i3 ← base - i2
    ok (i1, i3)
  | aeneas_test.Grade.Perfect => ok (base, 0#u32)

/-- [lnmai_core::aeneas_test::Duration]
    Source: 'src/aeneas_test.rs', lines 54:0-56:1
    Visibility: public -/
structure aeneas_test.Duration where
  micros : Std.I64

/-- [lnmai_core::aeneas_test::{impl core::fmt::Debug for lnmai_core::aeneas_test::Duration}::fmt]:
    Source: 'src/aeneas_test.rs', lines 53:9-53:14
    Visibility: public -/
def aeneas_test.Duration.Insts.CoreFmtDebug.fmt
  (self : aeneas_test.Duration) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugI64) self.micros
  core.fmt.Formatter.debug_struct_field1_finish f (toStr "Duration") (toStr
    "micros") dyn

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::fmt::Debug for lnmai_core::aeneas_test::Duration}]
    Source: 'src/aeneas_test.rs', lines 53:9-53:14 -/
@[reducible]
def aeneas_test.Duration.Insts.CoreFmtDebug : core.fmt.Debug
  aeneas_test.Duration := {
  fmt := aeneas_test.Duration.Insts.CoreFmtDebug.fmt
}

/-- [lnmai_core::aeneas_test::{impl core::clone::Clone for lnmai_core::aeneas_test::Duration}::clone]:
    Source: 'src/aeneas_test.rs', lines 53:16-53:21
    Visibility: public -/
def aeneas_test.Duration.Insts.CoreCloneClone.clone
  (self : aeneas_test.Duration) : Result aeneas_test.Duration := do
  ok self

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::clone::Clone for lnmai_core::aeneas_test::Duration}]
    Source: 'src/aeneas_test.rs', lines 53:16-53:21 -/
@[reducible]
def aeneas_test.Duration.Insts.CoreCloneClone : core.clone.Clone
  aeneas_test.Duration := {
  clone := aeneas_test.Duration.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::marker::Copy for lnmai_core::aeneas_test::Duration}]
    Source: 'src/aeneas_test.rs', lines 53:23-53:27 -/
@[reducible]
def aeneas_test.Duration.Insts.CoreMarkerCopy : core.marker.Copy
  aeneas_test.Duration := {
  cloneInst := aeneas_test.Duration.Insts.CoreCloneClone
}

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::marker::StructuralPartialEq for lnmai_core::aeneas_test::Duration}]
    Source: 'src/aeneas_test.rs', lines 53:29-53:38 -/
@[reducible]
def aeneas_test.Duration.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq aeneas_test.Duration := {
}

/-- [lnmai_core::aeneas_test::{impl core::cmp::PartialEq<lnmai_core::aeneas_test::Duration> for lnmai_core::aeneas_test::Duration}::eq]:
    Source: 'src/aeneas_test.rs', lines 53:29-53:38
    Visibility: public -/
def aeneas_test.Duration.Insts.CoreCmpPartialEqDuration.eq
  (self : aeneas_test.Duration) (other : aeneas_test.Duration) :
  Result Bool
  := do
  ok (self.micros = other.micros)

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::PartialEq<lnmai_core::aeneas_test::Duration> for lnmai_core::aeneas_test::Duration}]
    Source: 'src/aeneas_test.rs', lines 53:29-53:38 -/
@[reducible]
def aeneas_test.Duration.Insts.CoreCmpPartialEqDuration : core.cmp.PartialEq
  aeneas_test.Duration aeneas_test.Duration := {
  eq := aeneas_test.Duration.Insts.CoreCmpPartialEqDuration.eq
}

/-- [lnmai_core::aeneas_test::{impl core::cmp::Eq for lnmai_core::aeneas_test::Duration}::assert_fields_are_eq]:
    Source: 'src/aeneas_test.rs', lines 53:40-53:42
    Visibility: public -/
def aeneas_test.Duration.Insts.CoreCmpEq.assert_fields_are_eq
  (self : aeneas_test.Duration) : Result Unit := do
  ok ()

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::Eq for lnmai_core::aeneas_test::Duration}]
    Source: 'src/aeneas_test.rs', lines 53:40-53:42 -/
@[reducible]
def aeneas_test.Duration.Insts.CoreCmpEq : core.cmp.Eq aeneas_test.Duration
  := {
  partialEqInst := aeneas_test.Duration.Insts.CoreCmpPartialEqDuration
  assert_fields_are_eq :=
    aeneas_test.Duration.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [lnmai_core::aeneas_test::{impl core::cmp::Ord for lnmai_core::aeneas_test::Duration}::cmp]:
    Source: 'src/aeneas_test.rs', lines 53:56-53:59
    Visibility: public -/
def aeneas_test.Duration.Insts.CoreCmpOrd.cmp
  (self : aeneas_test.Duration) (other : aeneas_test.Duration) :
  Result Ordering
  := do
  ok (core.cmp.impls.OrdI64.cmp self.micros other.micros)

/-- [lnmai_core::aeneas_test::{impl core::cmp::PartialOrd<lnmai_core::aeneas_test::Duration> for lnmai_core::aeneas_test::Duration}::partial_cmp]:
    Source: 'src/aeneas_test.rs', lines 53:44-53:54
    Visibility: public -/
def aeneas_test.Duration.Insts.CoreCmpPartialOrdDuration.partial_cmp
  (self : aeneas_test.Duration) (other : aeneas_test.Duration) :
  Result (Option Ordering)
  := do
  let o ← aeneas_test.Duration.Insts.CoreCmpOrd.cmp self other
  ok (some o)

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::PartialOrd<lnmai_core::aeneas_test::Duration> for lnmai_core::aeneas_test::Duration}]
    Source: 'src/aeneas_test.rs', lines 53:44-53:54 -/
@[reducible]
def aeneas_test.Duration.Insts.CoreCmpPartialOrdDuration : core.cmp.PartialOrd
  aeneas_test.Duration aeneas_test.Duration := {
  partialEqInst := aeneas_test.Duration.Insts.CoreCmpPartialEqDuration
  partial_cmp :=
    aeneas_test.Duration.Insts.CoreCmpPartialOrdDuration.partial_cmp
}

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::Ord for lnmai_core::aeneas_test::Duration}]
    Source: 'src/aeneas_test.rs', lines 53:56-53:59 -/
@[reducible]
def aeneas_test.Duration.Insts.CoreCmpOrd : core.cmp.Ord aeneas_test.Duration
  := {
  eqInst := aeneas_test.Duration.Insts.CoreCmpEq
  partialOrdInst := aeneas_test.Duration.Insts.CoreCmpPartialOrdDuration
  cmp := aeneas_test.Duration.Insts.CoreCmpOrd.cmp
}

/-- [lnmai_core::aeneas_test::{lnmai_core::aeneas_test::Duration}::from_micros]:
    Source: 'src/aeneas_test.rs', lines 59:4-61:5
    Visibility: public -/
def aeneas_test.Duration.from_micros
  (micros : Std.I64) : Result aeneas_test.Duration := do
  ok { micros }

/-- [lnmai_core::aeneas_test::{lnmai_core::aeneas_test::Duration}::to_micros]:
    Source: 'src/aeneas_test.rs', lines 63:4-65:5
    Visibility: public -/
def aeneas_test.Duration.to_micros
  (self : aeneas_test.Duration) : Result Std.I64 := do
  ok self.micros

/-- [lnmai_core::aeneas_test::TimePoint]
    Source: 'src/aeneas_test.rs', lines 70:0-72:1
    Visibility: public -/
structure aeneas_test.TimePoint where
  micros : Std.I64

/-- [lnmai_core::aeneas_test::{impl core::fmt::Debug for lnmai_core::aeneas_test::TimePoint}::fmt]:
    Source: 'src/aeneas_test.rs', lines 69:9-69:14
    Visibility: public -/
def aeneas_test.TimePoint.Insts.CoreFmtDebug.fmt
  (self : aeneas_test.TimePoint) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugI64) self.micros
  core.fmt.Formatter.debug_struct_field1_finish f (toStr "TimePoint") (toStr
    "micros") dyn

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::fmt::Debug for lnmai_core::aeneas_test::TimePoint}]
    Source: 'src/aeneas_test.rs', lines 69:9-69:14 -/
@[reducible]
def aeneas_test.TimePoint.Insts.CoreFmtDebug : core.fmt.Debug
  aeneas_test.TimePoint := {
  fmt := aeneas_test.TimePoint.Insts.CoreFmtDebug.fmt
}

/-- [lnmai_core::aeneas_test::{impl core::clone::Clone for lnmai_core::aeneas_test::TimePoint}::clone]:
    Source: 'src/aeneas_test.rs', lines 69:16-69:21
    Visibility: public -/
def aeneas_test.TimePoint.Insts.CoreCloneClone.clone
  (self : aeneas_test.TimePoint) : Result aeneas_test.TimePoint := do
  ok self

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::clone::Clone for lnmai_core::aeneas_test::TimePoint}]
    Source: 'src/aeneas_test.rs', lines 69:16-69:21 -/
@[reducible]
def aeneas_test.TimePoint.Insts.CoreCloneClone : core.clone.Clone
  aeneas_test.TimePoint := {
  clone := aeneas_test.TimePoint.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::marker::Copy for lnmai_core::aeneas_test::TimePoint}]
    Source: 'src/aeneas_test.rs', lines 69:23-69:27 -/
@[reducible]
def aeneas_test.TimePoint.Insts.CoreMarkerCopy : core.marker.Copy
  aeneas_test.TimePoint := {
  cloneInst := aeneas_test.TimePoint.Insts.CoreCloneClone
}

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::marker::StructuralPartialEq for lnmai_core::aeneas_test::TimePoint}]
    Source: 'src/aeneas_test.rs', lines 69:29-69:38 -/
@[reducible]
def aeneas_test.TimePoint.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq aeneas_test.TimePoint := {
}

/-- [lnmai_core::aeneas_test::{impl core::cmp::PartialEq<lnmai_core::aeneas_test::TimePoint> for lnmai_core::aeneas_test::TimePoint}::eq]:
    Source: 'src/aeneas_test.rs', lines 69:29-69:38
    Visibility: public -/
def aeneas_test.TimePoint.Insts.CoreCmpPartialEqTimePoint.eq
  (self : aeneas_test.TimePoint) (other : aeneas_test.TimePoint) :
  Result Bool
  := do
  ok (self.micros = other.micros)

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::PartialEq<lnmai_core::aeneas_test::TimePoint> for lnmai_core::aeneas_test::TimePoint}]
    Source: 'src/aeneas_test.rs', lines 69:29-69:38 -/
@[reducible]
def aeneas_test.TimePoint.Insts.CoreCmpPartialEqTimePoint : core.cmp.PartialEq
  aeneas_test.TimePoint aeneas_test.TimePoint := {
  eq := aeneas_test.TimePoint.Insts.CoreCmpPartialEqTimePoint.eq
}

/-- [lnmai_core::aeneas_test::{impl core::cmp::Eq for lnmai_core::aeneas_test::TimePoint}::assert_fields_are_eq]:
    Source: 'src/aeneas_test.rs', lines 69:40-69:42
    Visibility: public -/
def aeneas_test.TimePoint.Insts.CoreCmpEq.assert_fields_are_eq
  (self : aeneas_test.TimePoint) : Result Unit := do
  ok ()

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::Eq for lnmai_core::aeneas_test::TimePoint}]
    Source: 'src/aeneas_test.rs', lines 69:40-69:42 -/
@[reducible]
def aeneas_test.TimePoint.Insts.CoreCmpEq : core.cmp.Eq aeneas_test.TimePoint
  := {
  partialEqInst := aeneas_test.TimePoint.Insts.CoreCmpPartialEqTimePoint
  assert_fields_are_eq :=
    aeneas_test.TimePoint.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [lnmai_core::aeneas_test::{impl core::cmp::Ord for lnmai_core::aeneas_test::TimePoint}::cmp]:
    Source: 'src/aeneas_test.rs', lines 69:56-69:59
    Visibility: public -/
def aeneas_test.TimePoint.Insts.CoreCmpOrd.cmp
  (self : aeneas_test.TimePoint) (other : aeneas_test.TimePoint) :
  Result Ordering
  := do
  ok (core.cmp.impls.OrdI64.cmp self.micros other.micros)

/-- [lnmai_core::aeneas_test::{impl core::cmp::PartialOrd<lnmai_core::aeneas_test::TimePoint> for lnmai_core::aeneas_test::TimePoint}::partial_cmp]:
    Source: 'src/aeneas_test.rs', lines 69:44-69:54
    Visibility: public -/
def aeneas_test.TimePoint.Insts.CoreCmpPartialOrdTimePoint.partial_cmp
  (self : aeneas_test.TimePoint) (other : aeneas_test.TimePoint) :
  Result (Option Ordering)
  := do
  let o ← aeneas_test.TimePoint.Insts.CoreCmpOrd.cmp self other
  ok (some o)

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::PartialOrd<lnmai_core::aeneas_test::TimePoint> for lnmai_core::aeneas_test::TimePoint}]
    Source: 'src/aeneas_test.rs', lines 69:44-69:54 -/
@[reducible]
def aeneas_test.TimePoint.Insts.CoreCmpPartialOrdTimePoint :
  core.cmp.PartialOrd aeneas_test.TimePoint aeneas_test.TimePoint := {
  partialEqInst := aeneas_test.TimePoint.Insts.CoreCmpPartialEqTimePoint
  partial_cmp :=
    aeneas_test.TimePoint.Insts.CoreCmpPartialOrdTimePoint.partial_cmp
}

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::Ord for lnmai_core::aeneas_test::TimePoint}]
    Source: 'src/aeneas_test.rs', lines 69:56-69:59 -/
@[reducible]
def aeneas_test.TimePoint.Insts.CoreCmpOrd : core.cmp.Ord aeneas_test.TimePoint
  := {
  eqInst := aeneas_test.TimePoint.Insts.CoreCmpEq
  partialOrdInst := aeneas_test.TimePoint.Insts.CoreCmpPartialOrdTimePoint
  cmp := aeneas_test.TimePoint.Insts.CoreCmpOrd.cmp
}

/-- [lnmai_core::aeneas_test::{lnmai_core::aeneas_test::TimePoint}::from_micros]:
    Source: 'src/aeneas_test.rs', lines 75:4-77:5
    Visibility: public -/
def aeneas_test.TimePoint.from_micros
  (micros : Std.I64) : Result aeneas_test.TimePoint := do
  ok { micros }

/-- [lnmai_core::aeneas_test::{lnmai_core::aeneas_test::TimePoint}::to_micros]:
    Source: 'src/aeneas_test.rs', lines 79:4-81:5
    Visibility: public -/
def aeneas_test.TimePoint.to_micros
  (self : aeneas_test.TimePoint) : Result Std.I64 := do
  ok self.micros

/-- [lnmai_core::aeneas_test::judge_tap]:
    Source: 'src/aeneas_test.rs', lines 85:0-96:1
    Visibility: public -/
def aeneas_test.judge_tap
  (diff : aeneas_test.Duration) : Result aeneas_test.Grade := do
  let abs_diff ←
    if diff.micros < 0#i64
    then -. diff.micros
    else ok diff.micros
  if abs_diff <= 16667#i64
  then ok aeneas_test.Grade.Perfect
  else
    if abs_diff <= 50001#i64
    then ok aeneas_test.Grade.Great
    else
      if abs_diff <= 150003#i64
      then ok aeneas_test.Grade.Good
      else ok aeneas_test.Grade.Miss

/-- [lnmai_core::aeneas_test::ScoreState]
    Source: 'src/aeneas_test.rs', lines 100:0-104:1
    Visibility: public -/
structure aeneas_test.ScoreState where
  combo : Std.U32
  perfect_combo : Std.U32
  total_score : Std.U32

/-- [lnmai_core::aeneas_test::{impl core::fmt::Debug for lnmai_core::aeneas_test::ScoreState}::fmt]:
    Source: 'src/aeneas_test.rs', lines 99:9-99:14
    Visibility: public -/
def aeneas_test.ScoreState.Insts.CoreFmtDebug.fmt
  (self : aeneas_test.ScoreState) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU32 self.combo
  let dyn1 := Dyn.mk _ core.fmt.DebugU32 self.perfect_combo
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self.total_score
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "ScoreState") (toStr
    "combo") dyn (toStr "perfect_combo") dyn1 (toStr "total_score") dyn2

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::fmt::Debug for lnmai_core::aeneas_test::ScoreState}]
    Source: 'src/aeneas_test.rs', lines 99:9-99:14 -/
@[reducible]
def aeneas_test.ScoreState.Insts.CoreFmtDebug : core.fmt.Debug
  aeneas_test.ScoreState := {
  fmt := aeneas_test.ScoreState.Insts.CoreFmtDebug.fmt
}

/-- [lnmai_core::aeneas_test::{impl core::clone::Clone for lnmai_core::aeneas_test::ScoreState}::clone]:
    Source: 'src/aeneas_test.rs', lines 99:16-99:21
    Visibility: public -/
def aeneas_test.ScoreState.Insts.CoreCloneClone.clone
  (self : aeneas_test.ScoreState) : Result aeneas_test.ScoreState := do
  ok self

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::clone::Clone for lnmai_core::aeneas_test::ScoreState}]
    Source: 'src/aeneas_test.rs', lines 99:16-99:21 -/
@[reducible]
def aeneas_test.ScoreState.Insts.CoreCloneClone : core.clone.Clone
  aeneas_test.ScoreState := {
  clone := aeneas_test.ScoreState.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::marker::Copy for lnmai_core::aeneas_test::ScoreState}]
    Source: 'src/aeneas_test.rs', lines 99:23-99:27 -/
@[reducible]
def aeneas_test.ScoreState.Insts.CoreMarkerCopy : core.marker.Copy
  aeneas_test.ScoreState := {
  cloneInst := aeneas_test.ScoreState.Insts.CoreCloneClone
}

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::marker::StructuralPartialEq for lnmai_core::aeneas_test::ScoreState}]
    Source: 'src/aeneas_test.rs', lines 99:29-99:38 -/
@[reducible]
def aeneas_test.ScoreState.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq aeneas_test.ScoreState := {
}

/-- [lnmai_core::aeneas_test::{impl core::cmp::PartialEq<lnmai_core::aeneas_test::ScoreState> for lnmai_core::aeneas_test::ScoreState}::eq]:
    Source: 'src/aeneas_test.rs', lines 99:29-99:38
    Visibility: public -/
def aeneas_test.ScoreState.Insts.CoreCmpPartialEqScoreState.eq
  (self : aeneas_test.ScoreState) (other : aeneas_test.ScoreState) :
  Result Bool
  := do
  if self.combo = other.combo
  then
    if self.perfect_combo = other.perfect_combo
    then ok (self.total_score = other.total_score)
    else ok false
  else ok false

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::PartialEq<lnmai_core::aeneas_test::ScoreState> for lnmai_core::aeneas_test::ScoreState}]
    Source: 'src/aeneas_test.rs', lines 99:29-99:38 -/
@[reducible]
def aeneas_test.ScoreState.Insts.CoreCmpPartialEqScoreState :
  core.cmp.PartialEq aeneas_test.ScoreState aeneas_test.ScoreState := {
  eq := aeneas_test.ScoreState.Insts.CoreCmpPartialEqScoreState.eq
}

/-- [lnmai_core::aeneas_test::{impl core::cmp::Eq for lnmai_core::aeneas_test::ScoreState}::assert_fields_are_eq]:
    Source: 'src/aeneas_test.rs', lines 99:40-99:42
    Visibility: public -/
def aeneas_test.ScoreState.Insts.CoreCmpEq.assert_fields_are_eq
  (self : aeneas_test.ScoreState) : Result Unit := do
  ok ()

/-- Trait implementation: [lnmai_core::aeneas_test::{impl core::cmp::Eq for lnmai_core::aeneas_test::ScoreState}]
    Source: 'src/aeneas_test.rs', lines 99:40-99:42 -/
@[reducible]
def aeneas_test.ScoreState.Insts.CoreCmpEq : core.cmp.Eq aeneas_test.ScoreState
  := {
  partialEqInst := aeneas_test.ScoreState.Insts.CoreCmpPartialEqScoreState
  assert_fields_are_eq :=
    aeneas_test.ScoreState.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [lnmai_core::aeneas_test::{lnmai_core::aeneas_test::ScoreState}::new]:
    Source: 'src/aeneas_test.rs', lines 107:4-113:5
    Visibility: public -/
def aeneas_test.ScoreState.new : Result aeneas_test.ScoreState := do
  ok { combo := 0#u32, perfect_combo := 0#u32, total_score := 0#u32 }

/-- [lnmai_core::aeneas_test::update_score]:
    Source: 'src/aeneas_test.rs', lines 117:0-124:1
    Visibility: public -/
def aeneas_test.update_score
  (state : aeneas_test.ScoreState) (base : Std.U32) (grade : aeneas_test.Grade)
  :
  Result aeneas_test.ScoreState
  := do
  let (earned, _) ← aeneas_test.compute_score base grade
  let b ←
    aeneas_test.Grade.Insts.CoreCmpPartialEqGrade.eq grade
      aeneas_test.Grade.Miss
  let (state1, i) ←
    if b
    then ok (state, 0#u32)
    else do
         let i1 ← state.combo + 1#u32
         ok (state, i1)
  let b1 ←
    aeneas_test.Grade.Insts.CoreCmpPartialEqGrade.eq grade
      aeneas_test.Grade.Perfect
  let (state2, i1) ←
    if b1
    then do
         let i2 ← state1.perfect_combo + 1#u32
         ok (state1, i2)
    else ok (state1, 0#u32)
  let i2 ← state2.total_score + earned
  ok { combo := i, perfect_combo := i1, total_score := i2 }

end lnmai_core
