-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lnmai_core]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [core::num::error::ParseIntError]
    Source: '/rustc/library/core/src/num/error.rs', lines 74:0-74:24
    Name pattern: [core::num::error::ParseIntError]
    Visibility: public -/
@[rust_type "core::num::error::ParseIntError"]
axiom core.num.error.ParseIntError : Type

/-- [core::str::iter::Split]
    Source: '/rustc/library/core/src/str/iter.rs', lines 492:8-492:91
    Name pattern: [core::str::iter::Split]
    Visibility: public -/
@[rust_type "core::str::iter::Split"]
axiom core.str.iter.Split {P : Type} (patternPatternInst :
  sorry /- Could not find: trait_decl_id: 18-/ P) : Type

/-- [core::str::pattern::CharSearcher]
    Source: '/rustc/library/core/src/str/pattern.rs', lines 370:0-370:27
    Name pattern: [core::str::pattern::CharSearcher]
    Visibility: public -/
@[rust_type "core::str::pattern::CharSearcher"]
axiom core.str.pattern.CharSearcher : Type

/-- [serde_json::error::Error]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_json-1.0.150/src/error.rs', lines 17:0-17:16
    Name pattern: [serde_json::error::Error]
    Visibility: public -/
@[rust_type "serde_json::error::Error"]
axiom serde_json.error.Error : Type

/-- [serde_json::map::Map]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_json-1.0.150/src/map.rs', lines 29:0-29:20
    Name pattern: [serde_json::map::Map]
    Visibility: public -/
@[rust_type "serde_json::map::Map"]
axiom serde_json.map.Map (K : Type) (V : Type) : Type

/-- [serde_json::number::Number]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_json-1.0.150/src/number.rs', lines 22:0-22:17
    Name pattern: [serde_json::number::Number]
    Visibility: public -/
@[rust_type "serde_json::number::Number"]
axiom serde_json.number.Number : Type

